version: 1.{build}
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
clone_folder: C:\wafter
init:
- ps: >-
    Install-Product node $env:nodejs_version $env:platform
environment:
  nodejs_version: 10
platform:
  - x86
  - x64
install:
- cmd: >-
    npm install
before_build:
- ps: >-
    .\hestia.ps1 > $null
build_script:
- cmd: >-
    # Hard code production mode
    set NODE_ENV=production
    
    npm run pkg

    cd dist\

    7z a "wafter-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip" wafter.exe
test: off
artifacts:
- path: dist\wafter-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip
  name: Wafter-%PLATFORM%